### PR TITLE
Added ABA_ROUTING_NUMBER test cases

### LINKED ISSUE #6: Detect ABA_ROUTING_NUMBER
### Description
The ABA_ROUTING_NUMBER is a nine-digit code used to identify U.S banks for checks, direct deposits and transfers. It is considered personally identifiable information because it is linked to bank accounts which is sensitive information that should be protected. For more information see [here](https://www.aba.com/news-research/analysis-guides/routing-number-policy-procedures).
### Detection Steps
ABA_ROUTING_NUMBER is a nine-digit code. The first two digits indicate Federal Reserve district or regional processing center and range from 00 - 12, 21 to 32, or 61 to 72. The last digit is a checksum where the first, fourth and seventh digits are multiplied by three. The second, fifth and eighth digits are multiplied by seven. The third and sixth digits are multiplied by one. The total is summed and the ninth digit is the number that makes the total divisible by 10.

### PR DESCRIPTION
**Pull request by naomirross**

### CODE REVIEW

**Comment by naomirross** [comment]
I had this error before and I resolved it by editing the pii_scan.py file similar to Brandon as seen [here](https://github.com/NCATComp410/comp410_fall_2024/pull/53/commits/f037ee5f39b09c87f9947ade10e7130ec09c90b2). I'm not sure how else to resolve it without those changes @claesmk

**Review by NiyaHen7 — COMMENTED** [review]
Yes, I'm not quite sure how to resolve this error either. Everything looks similar to Brandon's implementation.

**Review by claesmk — APPROVED** [review]
It looks like someone removed AbaRoutingRecognizer from the list of default recognizers.  I added it manually.  I think everything works as expected now.

**Review by anrichardson1 — APPROVED** [review]
looks good to go!

**Pull request merged**
