### PR TITLE
Added MEDICAL_LISENCE test cases

### LINKED ISSUE #12: Detect MEDICAL_LICENSE
**Description** 

Every medical specialist has to obtain a medical license to legally practice. 

**Detection Steps** 

There are many different patterns for medical license numbers. Using regular expressions to pattern match the most common medical lisence numbers will be the best course of action. In North Carolina the medical license numbers contain 5-6 numbers and no letters. Those are examples of patterns I will check for.

### PR DESCRIPTION
**Pull request by zjpittman**

### CODE REVIEW

**Comment by c-rubio** [comment]
I like the generation of medical licenses with a smaller list by mixing and matching. I also ran your tests and your tests pass (this is good since you're also checking the score so we know everything matches up). 

However, you have some commented out code that isn't being used; if you commit and push a change to your branch with some edits it should be reflected here. However, I don't think it's strictly necessary for this assignment, especially since your tests function and such. 

I approve of merging this 👍 Let's wait for the final approval from @claesmk and get this new functionality added 😎

**Review by claesmk — APPROVED** [review]
The score probably should be a 0.4 but Presidio is returning a 1.0, which could be a bug in Presidio.  This will take some time to investigate further, we can do that in the next sprint.

**Comment by claesmk** [comment]
Actually I see what's happening.  It matches the regex and then [validates](https://github.com/microsoft/presidio/blob/cc31bb61982311d7e2ad7e3b5334da797cdb6f98/presidio-analyzer/presidio_analyzer/predefined_recognizers/medical_license_recognizer.py#L52) the result - once that happens the score increases to 1.0

**Review by c-rubio — APPROVED** [review]
Just the comment to confirm that I approved the change for merge. We can handle any minor things in the next sprint, looks good!

**Comment by siblount** [comment]
@ChanningBarnes what are your thoughts on this?

**Comment by ChanningBarnes** [comment]
Ran the tests on my machine as well and it looks good.

**Pull request merged**
