### PR TITLE
25 detect us passport

### PR DESCRIPTION
**Pull request by JorDaFool**

### CODE REVIEW

**Review by claesmk — CHANGES_REQUESTED** [review]
Your changes look great - good job checking scores

However, why did you remove all the other stub test functions? I would recommend adding them back.  If you don't there will be a lot of merge conflicts to manually resolve.

**Comment by JorDaFool** [comment]
> Your changes look great - good job checking scores
> 
> However, why did you remove all the other stub test functions? I would recommend adding them back. If you don't there will be a lot of merge conflicts to manually resolve.

I completely forgot I removed the other test functions for testing. I will add them back.

**Review by JorDaFool — COMMENTED** [review]
Added back the stub test functions

**Review by claesmk — APPROVED** [review]
@JorDaFool I would have reverted the stub functions *exactly* as they originally were, otherwise you will still get merge conflicts for the w/s and ordering differences.  I push this change for you

**Review by Bford123 — APPROVED** [review]
Great job Jordan!

**Pull request merged**
