### PR TITLE
Added IN_AADHAAR

### LINKED ISSUE #14: Detect IN_AADHAAR
### Description
AADHAAR is an Indian government-issued unique 12-digit individual identity number. It serves as proof of identity and address in India. It is free to enroll in and was created to eliminate fake and duplicate identities in government databases. To find more information click [here](https://www.uidai.gov.in/en/16-english-uk/aapka-aadhaar/14-what-is-aadhaar.html#:~:text=Aadhaar%20is%20a%2012%20digit%20individual%20identification%20number%20issued%20by,and%20address%2C%20anywhere%20in%20India.).

### Detection Steps
- Each individual will be given a single unique Aadhaar ID number
- Aadhaar will provide a universal identity infrastructure that can be used by any identity-based application 
- UIDAI will give Yes/No answers to any identity authentication queries
- AADHAAR also uses based face authentication to improve privacy [here](https://github.com/NCATComp410/comp410_fall_2024/issues/14)

### PR DESCRIPTION
**Pull request by Jolisa-dot**

### CODE REVIEW

**Review by AbdoulZeba — APPROVED** [review]

**Review by claesmk — CHANGES_REQUESTED** [review]
Why is test_in_pan() deleted in this PR?

**Review by claesmk — CHANGES_REQUESTED** [review]
You were not actually testing an valid numbers because you were not consdiering the validation [protocol](https://github.com/microsoft/presidio/blob/cc31bb61982311d7e2ad7e3b5334da797cdb6f98/presidio-analyzer/presidio_analyzer/predefined_recognizers/in_aadhaar_recognizer.py#L64) 

I added a valid number for you and adjusted the scores.  

You still need to add test_in_pan() back which seems to have been removed

**Comment by claesmk** [comment]
@Jolisa-dot let me know if you need any assistance getting this finished up

**Comment by Jolisa-dot** [comment]
> @Jolisa-dot let me know if you need any assistance getting this finished up

I have sent you an email.

**Review by claesmk — APPROVED** [review]

**Pull request merged**
