### PR TITLE
Added IT_IDENTITY_CARD test case

### LINKED ISSUE #23: Detect IT_IDENTITY_CARD
### Description
The Italian electronic identity card is an identification document issued to any Italian citizen and to legal aliens. The CIE is intended for both digital and physical identification. The biometric information is printed on an ID-1 card and stored in a contactless chip. For more information click [here](https://en.wikipedia.org/wiki/Italian_electronic_identity_card).

### Detection Steps
The microprocessor chip in the identity card contains the name, surname, place and date of birth, residency, holder's picture, and two fingerprints (one of each hand, only if the applicant is aged 12 or over) of the individual. 

Example: Jane Doe, New York, New York, New York Apartments Building 5.

### PR DESCRIPTION
**Pull request by ComicalTNM**

### CODE REVIEW

**Review by claesmk — COMMENTED** [review]
Why did you decide to import the presidio_analyzer rather than follow the examples which only require calling analyze_text? 

Why did you decide to create a custom recognizer rather than use the built-in one?

**Comment by Wbpatterson** [comment]
You need to ensure that you have a positive and negative test case similar to the examples in the video below.

instructions: https://youtu.be/kuZqYygfI2E

**Comment by ComicalTNM** [comment]
> Why did you decide to import the presidio_analyzer rather than follow the examples which only require calling analyze_text?
> 
> Why did you decide to create a custom recognizer rather than use the built-in one?

When I tried using the built in recognizer I got an error, so I had to create a custom one. I can try calling analyze text instead and see if it produces the same result.

**Comment by claesmk** [comment]
Can you explain what the error was?  I pushed some code containing test_it_identity_card_new() which seems to work ok.

**Comment by ComicalTNM** [comment]
> Can you explain what the error was? I pushed some code containing test_it_identity_card_new() which seems to work ok.

It was an attribute error when I first tried it

**Review by claesmk — CHANGES_REQUESTED** [review]
test_it_identity_card_new() was intended as an example for you to look at.  Please update your test case and remove test_it_identity_card_new()

**Comment by ComicalTNM** [comment]
> test_it_identity_card_new() was intended as an example for you to look at. Please update your test case and remove test_it_identity_card_new()

Changes have been made.

**Review by claesmk — APPROVED** [review]
Looks good to me

**Review by Wbpatterson — APPROVED** [review]

**Pull request merged**
