### PR TITLE
9 detect au abn

### LINKED ISSUE #9: Detect AU_ABN
# AU_ABN - Australian Business Number (ABN)

## Description:
The Australian Business Number (ABN) is a unique 11-digit identifier issued by the Australian Business Register (ABR) to businesses operating in Australia. This number is essential for businesses to interact with government agencies, the Australian Taxation Office (ATO), and to facilitate legal business operations such as invoicing, registering for Goods and Services Tax (GST), and other regulatory processes. Each ABN is unique to a business entity, and it helps identify the business for tax and commercial purposes.

## Detection Steps:

Detecting an Australian Business Number (ABN) involves several steps, which include a combination of pattern matching, contextual analysis, and checksum validation:

### 1. Pattern Match:
- The ABN is always an 11-digit number. To detect an ABN, a pattern match for a numeric sequence of exactly 11 digits is the first step.
- **Format:** It may be presented with or without spaces (e.g., "12345678901" or "12 345 678 901").
- **Regular Expression Example:** `\b\d{11}\b`

### 2. Contextual Analysis:
- After identifying a possible ABN using the pattern match, it's essential to analyze the context in which the number appears. This involves checking for surrounding keywords or phrases such as "ABN," "Australian Business Number," or "Tax ID" to confirm that the 11-digit number refers to an ABN and not another type of numeric sequence (such as a phone number or ID).
- **Example Phrases:** "Registered ABN," "ABN number," or "Business Tax Identifier."

### 3. Checksum Validation:
- The final step is to verify the legitimacy of the ABN using a checksum validation. This ensures that the detected number is a valid ABN, not just a random sequence of digits. The ABN has a specific mathematical validation algorithm:
  1. Subtract 1 from the first digit of the ABN.
  2. Multiply each digit of the ABN by a set of predetermined weights: `[10, 1, 3, 5, 7, 9, 11, 13, 15, 17, 19]`.
  3. Sum the results.
  4. Divide the sum by 89.
  5. If the remainder is zero, the ABN is valid.

For more information, visit the [Australian Business Register (ABR)](https://www.abr.gov.au/) website.

For more information on the ABN format and validation algorithm, refer to the [ABN Lookup – Checksum validation process] (https://abr.business.gov.au/Help/AbnFormat) and [ABR Technical Help – ABN format](https://www.abr.gov.au/knowledge-centre/help-and-support/abr-technical-help/abn-format).

### PR DESCRIPTION
**Pull request by bbyrd2021**

### CODE REVIEW

**Review by claesmk — APPROVED** [review]
I reverted some changes which were not necessary and would have caused merge conflicts for other teams. 

Your test looks good.

**Review by naomirross — APPROVED** [review]
Looks good to me!

**Comment by anrichardson1** [comment]
Everything runs smooth and looks great!

**Review by anrichardson1 — APPROVED** [review]
Everything runs smooth and looks great!

**Pull request merged**
